# Generated by Django 4.2.1 on 2023-05-16 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=300)),
                ('app_link', models.CharField(max_length=500)),
                ('points', models.IntegerField()),
                ('app_image', models.ImageField(blank=True, null=True, upload_to='app_images')),
                ('app_category', models.CharField(choices=[('EN', 'Entertainment'), ('SP', 'Sports')], max_length=2)),
                ('sub_category', models.CharField(choices=[('SM', 'Social Media'), ('MS', 'Music'), ('EC', 'Ecommerce')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='defaultuser.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_app_images_uploads')),
                ('is_completed', models.BooleanField(default=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='webapp.app')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appImages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
